Adding fixes for UNV export/import and win32 support (#6)
* fix osx-error:
```
../src/StdMeshers/StdMeshers_Cartesian_3D.cxx:1663:28: error: ordered comparison between pointer and zero ('const SMDS_MeshNode *' and 'int')
          if ( node.Node() > 0 )
```

* fix Win32 build failure
set suffix 'd' for debug builds with MSVC

* fix build failure with netgen 5.3.1

* handle opening unv on Windows created on Linux and vice versa

* proper fix to keep nodes order intact when exporting to UNV format
For more detailed information have a look here:
https://forum.freecadweb.org/viewtopic.php?f=10&t=27744&sid=9a966f15219a156c83f12be7ac055791&start=70#p233460

* Fix UNV file read which was broken due to missing cards

* backward-compatibility: add option to switch additional naming of libraries on or off

* set ENABLE_LIB_NAMING to OFF by default

* Minor format